CREATE TABLE "MFTR36"."CLAIMS" (
        "CLAIMNUMBER" INTEGER NOT NULL,
        "POLICYNUMBER" INTEGER,
        "CLAIMDATE" DATE,
        "PAID" INTEGER,
        "CVALUE " INTEGER,
        "CAUSE" VARCHAR(255),
        "OBSERVATIONS" VARCHAR(255),
         CONSTRAINT "CLAIMS_PK" PRIMARY KEY
         ("CLAIMNUMBER")
     )
     IN "TESTDB"."TESTTS9"
     AUDIT NONE
     DATA CAPTURE NONE;

    © 2020 GitHub, Inc.
    Help
